name: Release

on:
  push:
    branches: [dev]

jobs:
  build_linux:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Setup just
      #   uses: extractions/setup-just@v3
      - name: Install tools
        run: sudo apt-get install --yes --no-install-recommends musl-tools
      - name: Install rustup targets
        run: rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-gnu
      - name: Install cross
        run: |
          curl -Lo cross-x86_64-unknown-linux-gnu.tar.gz https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-gnu.tar.gz
          sudo tar xvzf cross-x86_64-unknown-linux-gnu.tar.gz
          mv cross /usr/local/bin/cross
          mv cross-util /usr/local/bin/cross-util


      - name: Build
        run: |
          cross build --release --target x86_64-unknown-linux-musl
          cross build --release --target aarch64-unknown-linux-gnu

      - name: Tar binary
        run: |
          tar -czvf slack-message-x86_64-unknown-linux-musl.tar.gz -C target/x86_64-unknown-linux-musl/release slack-message
          tar -czvf slack-message-aarch64-unknown-linux-gnu.tar.gz -C target/aarch64-unknown-linux-gnu/release slack-message
      - name: Generate SHA256 checksums
        run: |
          shasum -a 256 slack-message-x86_64-unknown-linux-musl.tar.gz > slack-message-x86_64-unknown-linux-musl.tar.gz.sha256
          shasum -a 256 slack-message-aarch64-unknown-linux-gnu.tar.gz > slack-message-aarch64-unknown-linux-gnu.tar.gz.sha256

      - name: Upload x86_64-unknown-linux-musl Artifact
        uses: actions/upload-artifact@v4
        with:
          name: slack-message-x86_64-unknown-linux-musl.tar.gz
          path: slack-message-x86_64-unknown-linux-musl.tar.gz
      - name: Upload x86_64-unknown-linux-musl Artifact SHA
        uses: actions/upload-artifact@v4
        with:
          name: slack-message-x86_64-unknown-linux-musl.tar.gz.sha256
          path: slack-message-x86_64-unknown-linux-musl.tar.gz.sha256
      - name: Upload aarch64-unknown-linux-gnu Artifact
        uses: actions/upload-artifact@v4
        with:
          name: slack-message-aarch64-unknown-linux-gnu.tar.gz
          path: slack-message-aarch64-unknown-linux-gnu.tar.gz
      - name: Upload aarch64-unknown-linux-gnu Artifact SHA
        uses: actions/upload-artifact@v4
        with:
          name: slack-message-aarch64-unknown-linux-gnu.tar.gz.sha256
          path: slack-message-aarch64-unknown-linux-gnu.tar.gz.sha256
