name: Rust Cross-Platform CI

on:
  push:
    branches: [dev]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-musl

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Rust
      #   uses: actions/setup-rust@v1
      #   with:
      #     rust-version: stable
      #     target: ${{ matrix.target }}

      - name: Install dependencies for musl
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Install dependencies for aarch64-unknown-linux-gnu
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Run tests (native only)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: cargo test --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/

